### ISSUE TITLE
Model changed from Pixel XL to Pixel

### ISSUE THREAD

**Issue by vegaman** [Magisk-Modules-Repo/Google_Assistant_Enabler#1]
Your latest commit changed the model from Pixel XL to Pixel, which causes issues for a bunch of apps on my phone - e.g. my banking/mobile payments app will no longer open because it looks like I'm using a different phone.

Was Pixel XL causing issues that Pixel doesn't have?

**Comment by stangri** [comment]
Hey @vegaman, my bad, didn't expect the change to cause havoc for other apps!

Change was due to the fact that I couldn't get the space to work with the new v10-introduced way of setting system props, so in 10.0.1 I switched back to the old way (which still works).

I've pushed the update to repo, try it and let me know.

**Comment by stangri** [comment]
Just a heads up -- the next version of this module (10.0.2) will no longer change phone model/manufacturer as it seems no longer required for Google Assistant to work. The legacy version (10.0.1) will be available for download from github.

**Comment by vegaman** [comment]
Awesome.
Hope commenting won't re-open this, just wanted to say thanks. I'll give it a go when I'm not so busy at work.
That should fix the other issues the mod had as well - namely youtube serving VP9 and Camera losing HDR+
